daily_statistic:
  cron: "5 0 * * *"
  class: "Charts::DailyStatistic"
  queue: critical

blockstatistic:
  cron: "*/10 * * * *"
  class: "Charts::BlockStatistic"
  queue: critical

epoch_statistic:
  cron: "*/30 * * * *"
  class: "Charts::EpochStatistic"
  queue: critical

chart_forked_event_processor:
  cron: "30 0 * * *"
  class: "Charts::ForkedEventProcessor"
  queue: critical