name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6.4
      run: |
        sudo apt-get update
        sudo apt-get install -y libreadline-dev zlib1g-dev rbenv ruby-build libsodium-dev
        sudo apt-get upgrade
        rbenv install -l
        sudo rbenv install 2.6.4
        sudo rbenv global 2.6.4
        sudo rbenv versions
        sudo apt autoremove
    - name: Build and test with Rake
      run: |
        sudo gem install bundler -v 2.0.1
        sudo rbenv rehash
        bundle install --jobs 4 --retry 3
        bundle exec rake
