name: Ruby

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6.4
      run: |
        curl -sSL https://get.rvm.io | bash -s stable
        rvm install ruby-2.6.4
    - name: Build and test with Rake
      run: |  
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake
