name: Ruby

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6.4
      run: |
        sudo apt-get update
        sudo apt-get install software-properties-common
        sudo apt-get install -y libsodium-dev
        sudo apt-add-repository -y ppa:rael-gc/rvm
        sudo apt-get install libpq-dev rvm
        sudo /usr/share/rvm/bin/rvm install "ruby-2.6.4"
        sudo /usr/share/rvm/bin/rvm use 2.6.4
        git clone https://github.com/bitcoin-core/secp256k1.git && cd secp256k1 && ./autogen.sh && ./configure && make && ./tests && sudo make install && cd ..
        sudo apt install postgresql postgresql-contrib
        sudo su - postgres
        psql -c 'create database "ckb_explorer_test";' -U postgres
    - name: Build and test with Rake
      run: |
        source /usr/share/rvm/scripts/rvm
        gem install bundler:2.0.1
        bundle install --jobs 4 --retry 3
        bundle exec rails db:create RAILS_ENV=test
        bundle exec rails db:migrate RAILS_ENV=test
        bundle exec rails test RAILS_ENV=test
