name: Ruby

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6.4
      run: |
        sudo apt-get install rbenv ruby-build
        echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
        exec $SHELL
        rbenv install 2.6.4
        rbenv global 2.6.4
    - name: Build and test with Rake
      run: |  
        sudo gem install bundler
        rbenv rehash
        bundle install --jobs 4 --retry 3
        bundle exec rake
